export enum FormActionType {
   //* Contact actions
   CONTACT_FORM_SUCCESS = '[KINACCESS] CONTACT_FORM_SUCCESS',
   CONTACT_FORM_UNCOMPLETED = '[KINACCESS] CONTACT_FORM_UNCOMPLETED',
   CONTACT_FORM_EMPTY = '[KINACCESS] CONTACT_FORM_EMPTY',

   //* Sign up actions
   SIGN_UP_SUCCESS = '[KINACCESS] SIGN_UP_SUCCESS',
   SIGN_UP_UNCOMPLETED = '[KINACCESS] SIGN_UP_UNCOMPLETED',
   SIGN_UP_EMPTY = '[KINACCESS] SIGN_UP_EMPTY',

   //* Sign in form
   SIGN_IN_SUCCESS = '[KINACCESS] SIGN_IN_SUCCESS',
   SIGN_IN_FAILED = '[KINACCESS] SIGN_IN_FAILED',

   //*Google auth
   GOOGLE_AUTH = '[KINACCESS] GOOGLE_AUTH',

   //*Logout
   LOGOUT = '[KINACCESS] LOGOUT'
}
