export enum userActionType {
   //*User related constants
   GET_USER_DATA_SUCCESS = '[KINACCESS] GET USER DATA SUCCESS',
   GET_USER_DATA_FAILED = '[KINACCESS] GET USER DATA FAILED',
   SET_USER_DATA_NULL = '[KINACCESS] SET_USER_DATA_NULL',
}
